### ISSUE TITLE
Standardize on `Async` suffix in methods

### ISSUE THREAD

**Issue by Tyrrrz** [bitwarden/passwordless-server#141]
Currently, we have a bit of a mess in terms of this convention. It would be nice to standardize. I personally vote to make all async methods end with the corresponding suffix, as is customary in C#.

Example:

- Has `...Async`:

https://github.com/passwordless/passwordless-server/blob/8eac1bbc5eabdecef791a3720ed83be80e884865/src/AdminConsole/Services/ISharedBillingService.cs#L7-L21

- Does not have `...Async`:

https://github.com/passwordless/passwordless-server/blob/e63d0293660c69e2ef91d4224685c35ad00cd5b5/src/AdminConsole/Services/TimedHostedService.cs#L37-L85

**Comment by Tyrrrz** [comment]
Apparently this can be enforced via `.editorconfig`:

https://stackoverflow.com/a/53973220

**Comment by jonashendrickx** [comment]
Maybe also worth mentioning:

- One class/interface per file.
- Class names should match file.
- Interfaces or other abstractions should be placed in an Abstractions folder/namespace? This would make it easier to browse implementations alphabetically.

**Comment by Tyrrrz** [comment]
> * Interfaces or other abstractions should be placed in an Abstractions folder/namespace? This would make it easier to browse implementations alphabetically.

I personally don't like that, I like to keep related things together (e.g. `IEventLogger` and all its implementations) rather than group files by arbitrary traits.
