### ISSUE TITLE
help: why used `ToListAsync()` is it possible to have 2 users with same Id?

### ISSUE THREAD

**Issue by pooya1380m** [bitwarden/passwordless-server#448]
https://github.com/bitwarden/passwordless-server/blob/57f912eeb6fe87097e1d2e0cf7d7469c13b0d753/src/Service/Storage/Ef/EfTenantStorage.cs#L83

 why used `ToListAsync()` is it possible to have 2 users with same Id? 
 can't we use `FirstOrDefaultAsync()` instead?

```c#
        var res = await db.Credentials.Where(c => c.UserId == userId).ToListAsync();

**Comment by jonashendrickx** [comment]
Because, a single user can have multiple credentials.

**Comment by pooya1380m** [comment]
thanks

> Because, a single user can have multiple credentials.
