### ISSUE TITLE
E-Mail settings for self-hosting

### ISSUE THREAD

**Issue by ellwoodb** [bitwarden/passwordless-server#712]
In a recent commit, it seems the ability to change the mailing settings via environment variables for the docker container when self hosting were removed.
I was just trying to run the container (tried both, building from source and the image on docker hub) and it doesn't take the mail settings, so it logs all mails to mails.md. 
Is there a way to bring this feature back for those of us self hosting this?

**Comment by ellwoodb** [comment]
The commit was the merge of pr #707

**Comment by jonashendrickx** [comment]
Hi @ellwoodb , check [the documentation](https://docs.passwordless.dev/guide/self-hosting/configuration.html#e-mail) now.

It should only take very little time to update your configuration.

I believe you may be updating using the `latest` tag, instead of `stable`. Consider sticking to `stable`.

**Comment by ellwoodb** [comment]
Hey @jonashendrickx, thank you very much! With the new variables it‘s working nicely. I‘ll close this issue now.

Yes, I was using the `latest` tag and now switched to `stable` thanks for clarifying.

Maybe, if you have time you could update the `settings.env` in the `self-host` directory to reflect the changes. I could also do that myself with a pr if that‘s allowed?

**Comment by jonashendrickx** [comment]
> Hey @jonashendrickx, thank you very much! With the new variables it‘s working nicely. I‘ll close this issue now.
> 
> Yes, I was using the `latest` tag and now switched to `stable` thanks for clarifying.
> 
> Maybe, if you have time you could update the `settings.env` in the `self-host` directory to reflect the changes. I could also do that myself with a pr if that‘s allowed?

There's no need! Thank you!

I've opened #724 to prevent this from happening again in the future. If I pull a docker image with the latest tag, I would assume it sort of to be production ready.

I've also clarified that this is a breaking change in the release notes.
